#!/usr/bin/env PYTHONHASHSEED=0 python

import os
import sys
import json
import argparse

from collections import OrderedDict

import botocore.translate


def main():
    parser = argparse.ArgumentParser()

    parser.add_argument('modelfile')
    parser.add_argument('--output', type=argparse.FileType('w'), default=sys.stdout)
    parser.add_argument('--regions-file')
    parser.add_argument('--retry-file')
    parser.add_argument('--enhancements-file')

    args = parser.parse_args()

    directory = os.path.dirname(os.path.abspath(args.modelfile))

    if args.regions_file is None:
        args.regions_file = os.path.join(directory, '_regions.json')

    if args.retry_file is None:
        args.retry_file = os.path.join(directory, '_retry.json')

    if args.enhancements_file is None:
        args.enhancements_file = args.modelfile.replace('.json', '.extra.json')

    model_files = botocore.translate.load_model_files(args)
    translated  = botocore.translate.translate(model_files)

    args.output.write(json.dumps(translated, indent=4, separators=(',', ': ')))


if __name__ == '__main__':
    main()
