# ($) is heavily used in Gen.Tree to force ormolu to make a better layout
- ignore:
    name: "Redundant $"
    within:
      - Gen.Tree

# Ignore camel-case warnings for modules containing explicit lenses
- ignore:
    name: "Use camelCase"
    within:
      - Amazonka.Auth.SSO
      - Amazonka.Data.Body
      - Amazonka.EC2.Internal
      - Amazonka.EC2.Metadata
      - Amazonka.Env
      - Amazonka.S3.Internal
      - Amazonka.Types
      - Amazonka.Waiter
