resolver:   nightly-2015-06-17
flags:      {}
extra-deps: []
packages:
  - core
  - amazonka
  - amazonka-autoscaling
  - amazonka-cloudformation
  - amazonka-cloudfront
  - amazonka-cloudhsm
  - amazonka-cloudsearch
  - amazonka-cloudsearch-domains
  - amazonka-cloudtrail
  - amazonka-cloudwatch
  - amazonka-cloudwatch-logs
  - amazonka-codedeploy
  - amazonka-cognito-identity
  - amazonka-cognito-sync
  - amazonka-config
  - amazonka-datapipeline
  - amazonka-directconnect
  - amazonka-ds
  - amazonka-dynamodb
  - amazonka-ec2
  - amazonka-ecs
  - amazonka-efs
  - amazonka-elasticache
  - amazonka-elasticbeanstalk
  - amazonka-elastictranscoder
  - amazonka-elb
  - amazonka-emr
  - amazonka-glacier
  - amazonka-iam
  - amazonka-importexport
  - amazonka-kinesis
  - amazonka-kms
  - amazonka-lambda
  - amazonka-ml
  - amazonka-opsworks
  - amazonka-rds
  - amazonka-redshift
  - amazonka-route53
  - amazonka-route53-domains
  - amazonka-s3
  - amazonka-sdb
  - amazonka-ses
  - amazonka-sns
  - amazonka-sqs
  - amazonka-ssm
  - amazonka-storagegateway
  - amazonka-sts
  - amazonka-support
  - amazonka-swf
  - amazonka-workspaces
