{-# LANGUAGE DeriveGeneric             #-}
{-# LANGUAGE FlexibleInstances         #-}
{-# LANGUAGE NoImplicitPrelude         #-}
{-# LANGUAGE OverloadedStrings         #-}
{-# LANGUAGE RecordWildCards           #-}
{-# LANGUAGE TemplateHaskell           #-}
{-# LANGUAGE TypeFamilies              #-}

{-# OPTIONS_GHC -fno-warn-unused-binds #-}

-- Module      : Network.AWS.IAM.V2010_05_08.UpdateSAMLProvider
-- Copyright   : (c) 2013-2014 Brendan Hay <brendan.g.hay@gmail.com>
-- License     : This Source Code Form is subject to the terms of
--               the Mozilla Public License, v. 2.0.
--               A copy of the MPL can be found in the LICENSE file or
--               you can obtain it at http://mozilla.org/MPL/2.0/.
-- Maintainer  : Brendan Hay <brendan.g.hay@gmail.com>
-- Stability   : experimental
-- Portability : non-portable (GHC extensions)

-- | Updates the metadata document for an existing SAML provider. This operation
-- requires Signature Version 4. https://iam.amazonaws.com/
-- ?Action=UpdateSAMLProvider
-- &Name=arn:aws:iam::123456789012:saml-metadata/MyUniversity
-- &SAMLProviderDocument=VGhpcyBpcyB3aGVyZSB5b3UgcHV0IHRoZSBTQU1MIHByb3ZpZGVyIG1ldGFkYXRhIGRvY3VtZW50
-- LCBCYXNlNjQtZW5jb2RlZCBpbnRvIGEgYmlnIHN0cmluZy4= &Version=2010-05-08
-- &AUTHPARAMS arn:aws:iam::123456789012:saml-metadata/MyUniversity
-- 29f47818-99f5-11e1-a4c3-27EXAMPLE804.
module Network.AWS.IAM.V2010_05_08.UpdateSAMLProvider where

import Control.Lens.TH (makeLenses)
import Network.AWS.Request.Query
import Network.AWS.IAM.V2010_05_08.Types
import Network.AWS.Prelude

data UpdateSAMLProvider = UpdateSAMLProvider
    { _usamlprSAMLProviderArn :: Text
      -- ^ The Amazon Resource Name (ARN) of the SAML provider to update.
    , _usamlprSAMLMetadataDocument :: Text
      -- ^ An XML document generated by an identity provider (IdP) that
      -- supports SAML 2.0. The document includes the issuer's name,
      -- expiration information, and keys that can be used to validate the
      -- SAML authentication response (assertions) that are received from
      -- the IdP. You must generate the metadata document using the
      -- identity management software that is used as your organization's
      -- IdP.
    } deriving (Show, Generic)

makeLenses ''UpdateSAMLProvider

instance ToQuery UpdateSAMLProvider where
    toQuery = genericQuery def

data UpdateSAMLProviderResponse = UpdateSAMLProviderResponse
    { _usamlpsSAMLProviderArn :: Maybe Text
      -- ^ The Amazon Resource Name (ARN) of the SAML provider that was
      -- updated.
    } deriving (Show, Generic)

makeLenses ''UpdateSAMLProviderResponse

instance FromXML UpdateSAMLProviderResponse where
    fromXMLOptions = xmlOptions

instance AWSRequest UpdateSAMLProvider where
    type Sv UpdateSAMLProvider = IAM
    type Rs UpdateSAMLProvider = UpdateSAMLProviderResponse

    request = post "UpdateSAMLProvider"
    response _ = xmlResponse
