#!/usr/bin/env bash

set -e

library="$1"

if [ -z "$library" ]; then
    echo "Usage: examples <LIBRARY>"
    exit 1
fi

path=$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)/../example

echo "Building dependencies..."

stack build amazonka-core amazonka-test amazonka "$library"

echo ":l <EXAMPLE_MODULE>"

exec stack ghci amazonka amazonka-core "$library" --ghc-options "-i${path}"
