#!/usr/bin/env bash

set -euo pipefail

library=( $(ls -d amazonka-*) )
library=( $(echo ${library[@]} | tr ' ' '\n' | sort | uniq -u) )

for config in stack-*.yaml; do
    echo "Updating ${config}"

    sed -i -e '/# GENERATED/,/# END GENERATED/d' "${config}"

    echo "# GENERATED" >> "${config}"
    echo "$(printf '  - %s\n' "${library[@]}")" >> "${config}"
    echo "# END GENERATED" >> "${config}"
done

echo "Done."
