#!/usr/bin/env bash

set -e

project=proj/amazonka
target=../amazonka-doc
platform=x86_64-linux
ghcver=$(ghc --version | awk '{print $NF}')
resolver=$(sed -n 's/^resolver: *\(.*\)$/\1/p' stack.yaml)

standalone-haddock --hyperlink-source -o $target \
 --package-db $HOME/.stack/snapshots/$platform/$resolver/$ghcver/pkgdb \
 --package-db $HOME/$project/.stack-work/install/$platform/$resolver/$ghcver/pkgdb \
 core amazonka*

{
    cat <<-HTML
    <!DOCTYPE html>
    <h1>Amazonka Library Documentation</h1>
    <ul>
HTML

    for dir in $(ls -d $target/*/); do
        file=$(basename $dir)
        cat <<-HTML
        <li><a href="${file}/index.html">${file}</a></li>
HTML
    done

    cat <<-HTML
    </ul>
HTML
} > $target/index.html

set -x

cd $target

git add .
git commit -am "Regenerating documentation"
git push origin gh-pages
