#!/usr/bin/env bash

set -e
set -x

ver=7.10.1
proj=$HOME/proj
doc=$proj/aws-doc
libs=$proj/amazonka/amazonka-*

standalone-haddock \
 -o $doc \
 --package-db $HOME/.ghc/x86_64-linux-$ver/package.conf.d \
 --package-db $proj/amazonka/.cabal-sandbox/x86_64-linux-ghc-$ver-packages.conf.d \
 amazonka core $libs

cd $doc

git checkout gh-pages || true
git add .
git commit -am "Updating"
git push origin gh-pages
