#!/usr/bin/env bash

set -euo pipefail

docs=( documentation )
core=( amazonka-core amazonka )
test=( amazonka-test )
examples=( amazonka-examples )

priority_=( s3 autoscaling elb sqs iam ec2 )
priority=${priority_[@]/#/amazonka-}

library_=( $(ls -d amazonka-*) )
library=( $(echo ${library_[@]} ${priority[@]} | tr ' ' '\n' | sort | uniq -u) )

entry() {
    local ver="$1"
    local lib="$2"

cat <<-ENTRY
    - env: GHCVER=${ver} LIBRARY=${lib}
      addons: { apt: { packages: [ghc-${ver}], sources: [hvr-ghc] } }
ENTRY
}

matrix() {
    local title="$1"
    declare -a versions=("${!2}")
    declare -a selected=("${!3}")

cat <<-TITLE

    # ${title}
TITLE

    for lib in ${selected[@]}; do
        for ver in ${versions[@]}; do
            entry $ver $lib
        done
    done
}

ghc_802=( 8.0.2 )
ghc_82=( 8.2 )
ghc_all=( 8.2 8.0.2 7.10.3 )

travis=".travis.yml"

echo "Updating ${travis}"

sed -i -e '/# GENERATED/,/# END GENERATED/d' "${travis}"

echo "# GENERATED"                       >> "${travis}"
matrix "Documentation" ghc_82[@] docs[@] >> "${travis}"
matrix "Core" ghc_all[@] core[@]         >> "${travis}"
matrix "Test" ghc_82[@] test[@]          >> "${travis}"
matrix "Priority" ghc_all[@] priority[@] >> "${travis}"
matrix "Remainder" ghc_82[@] library[@]  >> "${travis}"
matrix "Examples" ghc_82[@] examples[@]  >> "${travis}"
echo "# END GENERATED"                   >> "${travis}"

echo "Done."
