#!/usr/bin/env bash

set -e
set -x
set -o errexit

branch=$(git symbolic-ref -q HEAD)
branch=${branch##refs/heads/}
branch=${branch:-HEAD}

cabal configure --disable-tests

DOCDIR=`mktemp -d -t pages.XXXXXX`
cabal haddock --haddock-option=-o$DOCDIR

HEAD=`git rev-parse HEAD`

git checkout gh-pages

mv $DOCDIR/* .

git add *.html *.js *.css *.gif *.png
git commit -m "Generated documentation from $HEAD on $branch"
git push origin gh-pages
git checkout $branch
