#!/usr/bin/env bash

set -euo pipefail

pvp="$1"
semantic="$2"

if [ -z "$pvp" ] || [ -z "$semantic" ]; then
    echo "Usage: bump-version <VERSION> <DEPENDENCY>"
    exit 1
fi

specs=(
 amazonka/amazonka.cabal
 core/amazonka-core.cabal
 examples/amazonka-examples.cabal
 gen/amazonka-gen.cabal
 test/amazonka-test.cabal
 amazonka-s3-encryption/amazonka-s3-encryption.cabal
)

echo "Bumping version to $pvp and dependencies to == $semantic ..."

for cabal in ${specs[@]}; do
    sed -i"" "s/^\(version: *\).*$/\1$pvp/" $cabal
    sed -i"" "s/^\(.*amazonka-[a-z0-9]* *== *\)\([0-9\.]\+\*\)$/\1$semantic.*/" $cabal
    sed -i"" "s/^\(.*amazonka *== *\)\([0-9\.]\+\*\)$/\1$semantic.*/" $cabal
done

echo "Done."
