#!/usr/bin/env bash

set -euo pipefail

mkdir -p ~/.local/bin

travis_retry() {
    cmd=$*
    $cmd || (sleep 2 && $cmd) || (sleep 10 && $cmd)
}

fetch_stack_linux() {
    curl -sL https://www.stackage.org/stack/linux-x86_64 | \
        tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
}

setup_project() {
    stack --no-terminal --skip-ghc-check setup && \
        stack update
}

travis_retry fetch_stack_linux
travis_retry setup_project
