#!/usr/bin/env bash

set -e

docs=( documentation )
core=( amazonka-core amazonka )
test=( amazonka-test )
examples=( amazonka-examples )

priority_=( s3 autoscaling elb sqs iam ec2 )
priority=${priority_[@]/#/amazonka-}

library_=( $(ls -d amazonka-*) )
library=( $(echo ${library_[@]} ${priority[@]} | tr ' ' '\n' | sort | uniq -u) )

entry() {
    local ver="$1"
    local lib="$2"

cat <<-ENTRY
    - env: GHCVER=${ver} LIBRARY=${lib}
      addons: { apt: { packages: [ghc-${ver}], sources: [hvr-ghc] } }
ENTRY
}

matrix() {
    local title="$1"
    declare -a versions=("${!2}")
    declare -a selected=("${!3}")

cat <<-TITLE

    # ${title}
TITLE

    for lib in ${selected[@]}; do
        for ver in ${versions[@]}; do
            entry $ver $lib
        done
    done
}

ghc_710=( 7.10.2 )
ghc_all=( 7.10.2 7.8.4 )

matrix "Documentation" ghc_710[@] docs[@]
matrix "Core" ghc_all[@] core[@]
matrix "Test" ghc_710[@] test[@]
matrix "Priority" ghc_all[@] priority[@]
matrix "Remainder" ghc_710[@] library[@]
matrix "Examples" ghc_710[@] examples[@]
