#!/usr/bin/env bash

set -euo pipefail

GHCVER=${GHCVER?"GHCVER needs to be set."}
LIBRARY=${LIBRARY?"LIBRARY needs to be set."}

path=$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)

$path/travis-timeout \
    stack --no-terminal --skip-ghc-check --stack-yaml stack-$GHCVER.yaml setup

if [ "$LIBRARY" != "documentation" ]; then
    $path/travis-timeout \
        stack --no-terminal --skip-ghc-check --stack-yaml stack-$GHCVER.yaml build --test --fast -j1 --only-snapshot $LIBRARY
fi
