#!/usr/bin/env bash

set -e

target=doc
platform=x86_64-linux
ghcver=$(ghc --version | awk '{print $NF}')
resolver=$(sed -n 's/^resolver: *\(.*\)$/\1/p' stack.yaml)

standalone-haddock --hyperlink-source -o $target \
 --package-db $HOME/.stack/snapshots/$platform/$resolver/$ghcver/pkgdb \
 --package-db .stack-work/install/$platform/$resolver/$ghcver/pkgdb \
 core amazonka*

{
    cat <<-HTML
    <!DOCTYPE html>
    <h1>Amazonka Library Documentation</h1>
    <ul>
HTML

    for dir in $(ls -d $target/*/); do
        file=$(basename $dir)
        cat <<-HTML
        <li><a href="${file}/index.html">${file}</a></li>
HTML
    done

    cat <<-HTML
    </ul>
HTML
} > $target/index.html

set -x

cd $target

git init

git config user.name "Brendan Hay"
git config user.email "brendan.g.hay@gmail.com"

git add .
git commit -m "Travis CI documentation deploy"

git push --force --quiet "https://${DOC_TOKEN}@${DOC_REF}" master:gh-pages > /dev/null 2>&1
