#!/usr/bin/env bash

set -e

if [ "$TRAVIS_BRANCH" != "develop" ]; then
    echo "Ignoring documentation build for branch '$TRAVIS_BRANCH'."
    exit 0
fi

if [ -z "$DOC_TOKEN" ]; then
    echo "Ignoring documentation build due to missing token."
    exit 0
fi

GHCVER=${GHCVER?"GHCVER needs to be set."}
DOC_REF=${DOC_REF?"DOC_REF needs to be set."}
BUILD_ID=${TRAVIS_BUILD_ID?"TRAVIS_BUILD_ID needs to be set."}
BUILD_NUMBER=${TRAVIS_BUILD_NUMBER?"TRAVIS_BUILD_NUMBER needs to be set."}

path=$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)

output=doc
platform=x86_64-linux
resolver=$(sed -n 's/^resolver: *\(.*\)$/\1/p' stack-$GHCVER.yaml)

echo "Using resolver ${resolver}"

databases=( $(stack --stack-yaml stack-$GHCVER.yaml path | sed -n 's/^.*-pkg-db: *\(.*\)$/\1/p') )
databases=( "${databases[@]/#/--package-db }" )

echo "Using resolver ${resolver}"
echo "Using databases ${databases[@]}"

$path/travis-timeout \
    stack --no-terminal --skip-ghc-check --stack-yaml stack-$GHCVER.yaml install \
    standalone-haddock \
    hscolour

$path/travis-timeout \
    stack --no-terminal --skip-ghc-check --stack-yaml stack-$GHCVER.yaml build \
    core amazonka*

$path/travis-timeout \
    standalone-haddock --hyperlink-source -o $output \
    ${databases[@]} \
    core amazonka*

{
    cat <<-HTML
    <!DOCTYPE html>
    <h1>Amazonka Library Documentation</h1>
    <h4><a href="https://travis-ci.org/brendanhay/amazonka/builds/${BUILD_ID}">Build #${BUILD_NUMBER}</a></h4>
    <ul>
HTML

    for dir in $(ls -d $output/*/); do
        file=$(basename $dir)
        cat <<-HTML
        <li><a href="${file}/index.html">${file}</a></li>
HTML
    done

    cat <<-HTML
    </ul>
HTML
} > $output/index.html

set -x

cd $output

git init

git config user.name "Brendan Hay"
git config user.email "brendan.g.hay@gmail.com"

git add .
git commit -m "Travis CI documentation deploy $BUILD_NUMBER"

git push --force --quiet "https://${DOC_TOKEN}@${DOC_REF}" master:gh-pages > /dev/null 2>&1
