#!/usr/bin/env bash

set -euo pipefail

LIBRARY=${LIBRARY?"LIBRARY needs to be set."}

travis_retry() {
    cmd=$*
    $cmd || (sleep 2 && $cmd) || (sleep 10 && $cmd)
}

build_library() {
    stack --no-terminal --skip-ghc-check build \
        -j2                                    \
        --fast                                 \
        --test                                 \
        $LIBRARY
}

travis_retry build_library
