#!/usr/bin/env bash

set -e

dir=~/.local/bin
remote=https://github.com/commercialhaskell/stack/releases/download/v0.1.3.1/stack-0.1.3.1-x86_64-linux.gz
local=$dir/stack

mkdir -p $dir

curl -L $remote | gunzip > $local

chmod a+x $local

ghc --version
stack --version
