#!/usr/bin/env bash

set -e

name=${PACKAGE_NAME?"Required"}
version=${PACKAGE_VERSION?"Required"}

user=${HACKAGE_USER?"Required"}
password=${HACKAGE_PASS?"Required"}

package=${name}-${version}

set -x

cabal clean &&                                     \
 cabal configure &&                                \
 cabal build &&                                    \
 cabal haddock                                     \
     --hyperlink-source                            \
     --html-location='/package/$pkg-$version/docs' \
     --contents-location='/package/$pkg'

cd dist/doc/html

archive="${package}-docs"

cp -r "${name}" "${archive}" && \
 gtar -c -z -Hustar -f "${archive}.tar.gz" "${archive}"

curl -X PUT -H 'Content-Type: application/x-tar' \
    -H 'Content-Encoding: gzip' --data-binary "@${archive}.tar.gz" \
    "http://${user}:${password}@hackage.haskell.org/package/${package}/docs"
