#!/usr/bin/env bash

# Usage: format

# Run all formatters and linters to ensure codebase consistency

set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"

./format-bazel
./format-haskell
./format-nix
./format-shell

echo 'Done.'
