#!/usr/bin/env bash

# Usage: format

set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

./scripts/format-haskell
./scripts/format-bazel
./scripts/format-nix
./scripts/format-shell

echo "Done."
