#!/usr/bin/env bash

# Usage: format

# Run all formatters and linters ensuring codebase consistency

set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"

./format-haskell
./format-nix
./format-shell

echo 'Done.'
