#!/usr/bin/env bash

# Usage: format-json

set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

echo "Formatting JSON."

# Avoid the shell.nix dependency on moreutils, which will replace gnu parallel.
sponge() (
  case "$1" in
  -a | --append)
    append=1
    file="$2"
    ;;
  *)
    append=""
    file="$1"
    ;;
  esac

  awk -v append="$append" -v file="$file" '
NR == 1	{ lines = $0 }
NR != 1	{ lines = lines ORS $0 }
END	{
	if ( ! file ) { file = "-" }
	if ( append ) {
		print lines >> file;
	} else {
		print lines >  file;
	}
}'
)

shopt -s globstar

for file in configs/**/*.json; do
  printf '%s\n' "$file"
  python3 -m json.tool "$file" | sponge "$file"
done
