#!/usr/bin/env bash

# Usage: generate-all

set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

script="$(basename "$0")"

say() {
  echo "$1" >&2
}

usage() {
  cat >&2 <<EOF
  Usage:
    $script (-h|--help) (--no-format) [MODEL..]

  Synopsis:
    A wrapper around nix-build generate.nix that also copies the 
    resulting artefacts into their respective repository destinations 
    from the nix-store.

  Options:
    --no-format Don't run cabal-fmt and ormolu by skipping the formatPhase.
    -h|--help   Show this usage information.

  Examples:
    $script
    $script ec2 
    $script --no-format ec2 s3 cloudformation
EOF
}

format='true'
models=()

parse_options() {
  while test $# -gt 0; do
    case "$1" in
    --no-format)
      format='false'
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    -h*)
      usage
      exit 0
      ;;
    *)
      models+=("$1")
      ;;
    esac
    shift
  done
}

parse_options "$@"

args=(--no-out-link --arg format "$format")

if ! [ ${#models[@]} -eq 0 ]; then
  args+=(--arg models "[ $(printf '"%s" ' "${models[@]}")]")
fi

result=$(nix-build generate.nix "${args[@]}")

say "copying $result to lib..."

cp -r "$result"/* ./lib/

say "setting u+rw lib permissions..."

chmod -R u+rw ./lib

say "done."
