#!/usr/bin/env bash

# Usage: generate-configs
#
# Generates configuration for all services found in botocore that
# are missing corresponding configurations in ./config/services.
#
# The example configurations will be written to individual files under
# ./configs and ./annexes.

set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

# Output a message to stderr.
say() {
	echo >&2 "$@"
}

botocore="vendor/botocore/botocore/data"
configs="./configs"
frequencies="./configs/word-frequencies"

say "Using botocore $botocore"
say "Using configs $configs"
say "Using word frequencies $frequencies"

exec cabal run amazonka-gen:exe:gen-configs -- "$botocore" \
	--configs "$configs" \
	--word-frequencies "$frequencies"
