#!/usr/bin/env bash

# Usage: pin-stackage
#
# Update the materialised //:stackage-snapshot.json from the `stack_snapshot`
# defined in WORKSPACE.

bazel run @stackage-gen-unpinned//:pin
bazel run @stackage-unpinned//:pin
