#!/usr/bin/env bash

# Usage: pin-stackage
#
# Update the materialised //:stackage-snapshot.json from the `stack_snapshot`
# defined in WORKSPACE.

bazel run @stackage-lts-18.10-unpinned//:pin
bazel run @stackage-lts-16.31-unpinned//:pin
