#!/bin/sh -eux

set -euo pipefail

if [ $# -ne 2 ]; then
  echo "Usage: bump-version <VERSION> <DEPENDENCY>"
  exit 1
fi

pvp="$1"
semantic="$2"

specs=(
  amazonka/amazonka.cabal
  core/amazonka-core.cabal
  examples/amazonka-examples.cabal
  gen/amazonka-gen.cabal
  test/amazonka-test.cabal
  amazonka-s3-encryption/amazonka-s3-encryption.cabal
)

echo "Bumping version to $pvp and dependencies to == $semantic ..."

for cabal in "${specs[@]}"; do
  sed -e "s/^\(version: *\).*$/\1$pvp/;" \
    -e "s/^\(.*amazonka-[a-z0-9]* *== *\)\([0-9\.]\+\*\)$/\1$semantic.*/" \
    -e "s/^\(.*amazonka *== *\)\([0-9\.]\+\*\)$/\1$semantic.*/" "$cabal" >"$cabal.new"

  mv "$cabal.new" "$cabal"
done

echo "Done."
