#!/usr/bin/env bash

# Usage: bump-version <VERSION> <DEPENDENCY>

set -euo pipefail

if [ $# -ne 2 ]; then
    echo "Usage: bump-version <VERSION> <DEPENDENCY>"
    exit 1
fi

pvp="$1"
sem="$2"

specs=(
    amazonka/amazonka.cabal
    amazonka-core/amazonka-core.cabal
    amazonka-gen/amazonka-gen.cabal
    amazonka-test/amazonka-test.cabal
    amazonka-s3-encryption/amazonka-s3-encryption.cabal
    amazonka-examples/amazonka-examples.cabal
)

echo "Bumping version to $pvp and dependencies to == $sem ..."

for cabal in "${specs[@]}"; do
    sed -e "s/^\(version: *\).*$/\1$pvp/;" \
        -e "s/^\(.*amazonka-[a-z0-9]* *== *\)\([0-9\.]\+\*\)$/\1$sem.*/" \
        -e "s/^\(.*amazonka *== *\)\([0-9\.]\+\*\)$/\1$sem.*/" $cabal >$cabal.new

    mv $cabal.new $cabal
done

echo "Done."
