#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

# Generate (or update) a corresponding BUILD file for every *.cabal file.
bazel run //:gazelle

# Update the WORKSPACE's stack_snapshot with any haskell dependencies.
bazel run //:gazelle-update-repos

# Rewrite the haskell_doc documentation target to include any new packages.
bazel run --run_under "cd $PWD &&" @com_github_bazelbuild_buildtools//buildozer -- \
  "set deps $(bazel query 'kind("haskell_library", //lib/...)')" \
  //docs:docs
